### ISSUE TITLE
Example 12 uses an undefined setDataFrom() method

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-worker#23]
Example 12 uses `setDataFrom()` method which is not defined in the spec. I believe this should be `mapDataInto()` instead, correct @kakukogou?

```
// write back to event outputImageBitmap
  outputBitmap.setDataFrom("RGBA32", rgbaBuffer, 0, rgbaBufferLength,
                           bitmap.width, bitmap.height, bitmapPixelLayout.channels[0].stride);
}
```

**Comment by kakukogou** [comment]
Sorry that the `ImageBitmap.setDataFrom()` is a deprecated design and the examples is not updated accordingly.

The `setDataFrom()` method is not suitable since we don't want to make an ImageBitmap mutable and instead, we proposed the following method of `ImageBitmapFactory` to let users to create a new `ImageBitmap` from their own `ArrayBuffer`.

```
ImageBitmapFactory::Promise<ImageBitmap> createImageBitmap (BufferSource buffer, long offset, long length, ImageFormat format, ImageFormatPixelLayout layout);
```

So, the sample code be modified as something likes the follow code snippet:

```
// write back to event outputImageBitmap
  outputBitmap = createImageBitmap(rgbaBuffer, 0, rgbaBufferLength, "RGBA32", bitmapPixelLayout);
}
```

I know that this code snippet does not really fit into the current sample code, how about you leave the sample code as it is and I modify it after #22 ?

**Comment by anssiko** [comment]
Thanks for the explanation. I'll try to finish #22 soon so you can fix the example.
