### ISSUE TITLE
Add constructors to both ChannelPixelLayout and ImageFormatPixelLayout

### ISSUE THREAD

**Issue by kakukogou** [w3c/mediacapture-worker#25]
Before I can proceed #23, I would like to introduce constructors to both `ChannelPixelLayout` and `ImageFormatPixelLayout`. Because it is very likely that the formats of `VideoProcessorEvent::inputImageBitmap` and `VideoProcessorEvent::outputImageBitmap` are different.  So, if users have to use `ImageBitmapFactories::createImageBitmap(FromSourceBuffer)`, they need a way to create `ChannelPixelLayout` and `ImageFormatPixelLayout` objects. Thoughts? @anssiko and @ChiahungTai.

**Comment by kakukogou** [comment]
If "adding constructors" is the right way, then the constructor APIs will be something likes the following.

```
[Exposed=(Window,Worker),
 Constructor(unsigned long offset, unsigned long width, unsigned long height, DataType dataType, unsigned long stride, unsigned long skip)]
interface ChannelPixelLayout {
    readonly    attribute unsigned long offset;
    readonly    attribute unsigned long width;
    readonly    attribute unsigned long height;
    readonly    attribute DataType      dataType;
    readonly    attribute unsigned long stride;
    readonly    attribute unsigned long skip;
};
```

```
[Exposed=(Window,Worker),
 Constructor(ChannelPixelLayout[] channels)]
interface ImageFormatPixelLayout {
    readonly    attribute ChannelPixelLayout[] channels;
};
```

**Comment by anssiko** [comment]
Sounds good to me. We need to also then define what are the default values, something like:

The ChannelPixelLayout() constructor, when invoked, must return a newly created ChannelPixelLayout object. [...]

When the ChannelPixelLayout object is created, the offset attribute must be set to [...] etc.

**Comment by kakukogou** [comment]
Does it mean that we also need to remove the "readonly" of all the properties (offset, width, height, dataType, stride, skip and channels) if we provide default constructors?

**Comment by kakukogou** [comment]
I think I misunderstood your idea. You are not talking about providing a default constructor but the process of invoking the explicit constructor, right?

**Comment by anssiko** [comment]
The attributes can be `readonly` if the intended behaviour is they can only be set when the object is constructed, and not modified afterwards. Since all the constructor's arguments are mandatory, I think we simplify and say:

The `ChannelPixelLayout(offset, width, height, dataType, stride, skip)` constructor, when invoked, must create and return a `ChannelPixelLayout` object whose `<a>`offset`</a>` is set the given `<var>`offset`</var>` argument, whose `<a>`width`</a>` is set [...]

If the constructor is called with too few arguments (or arguments of wrong type), it'll throw a `TypeError`. That's covered by WebIDL and we do not need to add any spec language for it.

**Comment by kakukogou** [comment]
Oh, great, then I think I am on the right way!
